dist: xenial
language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test api/server/* -v -cover -race
  - $HOME/gopath/bin/goveralls -ignore "proto/*" -service=travis-ci
